# docker-compose.test.yml
version: '3.8'

services:
  # Nomes de serviço simplificados (iguais aos de prod, mas isolados pela rede)
  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Maceio
    volumes:
      # Volume isolado para o banco de dados de teste
      - mysql_data_test:/var/lib/mysql
      # Mesmo diretório de scripts, será executado no contexto deste container
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    ports:
      # Expõe na porta de teste definida no .env.test
      - "${DB_PORT_TEST}:3306"
    networks:
      - app-network-test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080" # Porta interna
    environment:
      PORT: 8080
      DB_HOST: mysql_db # Aponta para o serviço mysql_db desta rede de teste
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app-network-test

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      # Expõe a porta interna 80 do Nginx na porta de teste do host
      - "${HOST_PORT_HTTP_TEST}:80"
    environment:
      VITE_BACKEND_URL: /api
    depends_on:
      - backend
    networks:
      - app-network-test

networks:
  # Rede exclusiva para o ambiente de teste
  app-network-test:
    driver: bridge

volumes:
  # Volume exclusivo para o banco de dados de teste
  mysql_data_test: