version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: mysql_db # Host do MySQL dentro da rede Docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LOG_DEBUG_MODE: "true"
    depends_on:
      - mysql_db
    volumes:
      - ./backend:/app/backend
      # Se você vai usar SQLite, este volume é crucial para persistência
      # - ./dados.db:/app/dados.db
    networks:
      - app-network
    # command: npm start # Descomente e ajuste se necessário, baseado no seu backend/package.json

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
      - "5173:5173" # Opcional para dev local
    environment:
      VITE_BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: