# docker-compose.test.yml

services:
  mysql_db_test: # Nome único para o serviço de BD de teste
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Maceio
    volumes:
      - mysql_data_test:/var/lib/mysql # Volume isolado para teste
    ports:
      - "${DB_PORT_TEST}:3306" # Usa a porta do .env.test (ex: 3307)
    networks:
      - app-network-test # Rede isolada para teste
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend_test: # Nome único
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080"
    environment:
      PORT: 8080
      DB_HOST: mysql_db_test # Aponta para o BD de teste
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql_db_test:
        condition: service_healthy
    networks:
      - app-network-test

  frontend_test: # Nome único
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${HOST_PORT_HTTP_TEST}:80" # Usa a porta do .env.test (ex: 8081)
    environment:
      VITE_BACKEND_URL: /api
    depends_on:
      - backend_test
    networks:
      - app-network-test

networks:
  app-network-test: # Rede isolada para teste
    driver: bridge

volumes:
  mysql_data_test: # Volume isolado para teste
