# docker-compose.prod.yml

services:
  mysql_db_prod: # Renomeado para evitar conflito de nome de serviço
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Maceio
    volumes:
      - mysql_data_prod:/var/lib/mysql # Volume de produção
    ports:
      - "${DB_PORT_PROD}:3306" # Usa a porta do .env.prod
    networks:
      - app-network-prod # Rede de produção
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend_prod: # Renomeado
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080" # A porta interna não precisa mudar
    environment:
      PORT: 8080
      DB_HOST: mysql_db_prod # Aponta para o BD de produção
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql_db_prod:
        condition: service_healthy
    networks:
      - app-network-prod

  frontend_prod: # Renomeado
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${HOST_PORT_HTTP_PROD}:80" # Usa a porta do .env.prod (ex: 80)
    environment:
      VITE_BACKEND_URL: /api
    depends_on:
      - backend_prod
    networks:
      - app-network-prod

networks:
  app-network-prod: # Rede de produção
    driver: bridge

volumes:
  mysql_data_prod: # Volume de produção
